apiVersion: batch/v1
kind: Job
metadata:
  name: malware-training-job
spec:
  template:
    spec:
      containers:
        - name: trainer
          image: malware-trainer:latest
          imagePullPolicy: Never

          env:
            - name: USE_S3_DATA
              value: "true"

            - name: S3_BUCKET
              value: intrusion-ml-models

            - name: AWS_DEFAULT_REGION
              value: us-east-1

            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000

      restartPolicy: Never